"""
Enhanced Product Seed Script - 50+ Detailed Products for Marketplace
Includes laptops, courses, electronics, vehicles, property, and more
"""

from pymongo import MongoClient
from datetime import datetime
from bson import ObjectId

# MongoDB connection
MONGO_URI = 'mongodb://localhost:27017/'
DB_NAME = 'government_portal'

client = MongoClient(MONGO_URI)
db = client[DB_NAME]
products_collection = db.products

print("🔌 Connecting to MongoDB...")
print("✅ Connected to database")
print("=" * 60)

# Clear existing products
print("🗑️  Clearing existing products...")
products_collection.delete_many({})
print("✅ Cleared products collection")

# ========================================
# COMPREHENSIVE PRODUCT DATA (50+ items)
# ========================================

products = [
    # ==========================================
    # LAPTOPS & COMPUTERS (10 items)
    # ==========================================
    {
        'title': 'Dell XPS 15 - Premium Laptop',
        'description': '15.6" 4K OLED Display, Intel Core i7-13700H, 16GB RAM, 512GB SSD, NVIDIA GeForce RTX 4050. Perfect for professionals and content creators.',
        'price': 435000,
        'category': 'Electronics',
        'subcategory': 'Laptops',
        'brand': 'Dell',
        'image_url': 'https://example.com/images/dell-xps-15.jpg',
        'link_url': 'https://example.com/products/dell-xps-15',
        'stock': 15,
        'featured': True,
        'target_age_min': 25,
        'target_age_max': 45,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['software engineer', 'engineer', 'business owner', 'designer'],
        'target_categories': ['tech_enthusiast', 'tech_professional', 'electronics_buyer'],
        'keywords': ['laptop', 'computer', 'dell', 'xps', 'premium', 'professional', 'work', 'programming'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'MacBook Pro 14" M3 Pro',
        'description': 'Apple MacBook Pro 14" with M3 Pro chip, 18GB RAM, 512GB SSD. Liquid Retina XDR display. Perfect for developers and designers.',
        'price': 625000,
        'category': 'Electronics',
        'subcategory': 'Laptops',
        'brand': 'Apple',
        'image_url': 'https://example.com/images/macbook-pro-m3.jpg',
        'link_url': 'https://example.com/products/macbook-pro-m3',
        'stock': 8,
        'featured': True,
        'target_age_min': 25,
        'target_age_max': 50,
        'target_locations': ['Colombo'],
        'target_jobs': ['software engineer', 'designer', 'business owner'],
        'target_categories': ['tech_enthusiast', 'tech_professional', 'electronics_buyer', 'established_professional'],
        'keywords': ['laptop', 'macbook', 'apple', 'mac', 'professional', 'programming', 'design'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'ASUS ROG Gaming Laptop',
        'description': 'ASUS ROG Strix G16, Intel Core i9, 32GB RAM, 1TB SSD, RTX 4070 8GB. 165Hz display. Ultimate gaming performance.',
        'price': 550000,
        'category': 'Electronics',
        'subcategory': 'Laptops',
        'brand': 'ASUS',
        'image_url': 'https://example.com/images/asus-rog.jpg',
        'link_url': 'https://example.com/products/asus-rog',
        'stock': 12,
        'featured': True,
        'target_age_min': 18,
        'target_age_max': 35,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['student', 'software engineer', 'engineer'],
        'target_categories': ['tech_enthusiast', 'electronics_buyer', 'young_adult'],
        'keywords': ['gaming', 'laptop', 'asus', 'rog', 'computer', 'games', 'high performance'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'HP Pavilion 15 - Budget Laptop',
        'description': 'HP Pavilion 15, Intel Core i5-1235U, 8GB RAM, 512GB SSD. Great for students and everyday computing.',
        'price': 195000,
        'category': 'Electronics',
        'subcategory': 'Laptops',
        'brand': 'HP',
        'image_url': 'https://example.com/images/hp-pavilion.jpg',
        'link_url': 'https://example.com/products/hp-pavilion',
        'stock': 25,
        'featured': False,
        'target_age_min': 18,
        'target_age_max': 35,
        'target_locations': ['Colombo', 'Kandy', 'Galle', 'Negombo'],
        'target_jobs': ['student', 'teacher', 'engineer'],
        'target_categories': ['student', 'young_adult', 'tech_enthusiast'],
        'keywords': ['laptop', 'budget', 'student', 'affordable', 'hp', 'computer'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Lenovo ThinkPad X1 Carbon',
        'description': 'Business ultrabook, Intel Core i7, 16GB RAM, 512GB SSD. Lightweight, durable, 14" display. Perfect for professionals.',
        'price': 385000,
        'category': 'Electronics',
        'subcategory': 'Laptops',
        'brand': 'Lenovo',
        'image_url': 'https://example.com/images/thinkpad-x1.jpg',
        'link_url': 'https://example.com/products/thinkpad-x1',
        'stock': 10,
        'featured': False,
        'target_age_min': 28,
        'target_age_max': 55,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['business owner', 'manager', 'engineer', 'doctor'],
        'target_categories': ['tech_professional', 'business_owner', 'established_professional'],
        'keywords': ['laptop', 'business', 'professional', 'lenovo', 'thinkpad', 'work'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'MSI Creator Z16 - Content Creation',
        'description': 'MSI Creator Z16, Intel Core i9, 32GB RAM, 1TB SSD, RTX 4060. 16" QHD+ display. For video editing and design.',
        'price': 495000,
        'category': 'Electronics',
        'subcategory': 'Laptops',
        'brand': 'MSI',
        'image_url': 'https://example.com/images/msi-creator.jpg',
        'link_url': 'https://example.com/products/msi-creator',
        'stock': 6,
        'featured': True,
        'target_age_min': 22,
        'target_age_max': 40,
        'target_locations': ['Colombo'],
        'target_jobs': ['designer', 'software engineer', 'business owner'],
        'target_categories': ['tech_enthusiast', 'tech_professional', 'electronics_buyer'],
        'keywords': ['laptop', 'creator', 'video editing', 'design', 'content creation', 'professional'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Acer Aspire 5 - Value Laptop',
        'description': 'Acer Aspire 5, AMD Ryzen 5, 8GB RAM, 512GB SSD. 15.6" Full HD. Excellent value for money.',
        'price': 165000,
        'category': 'Electronics',
        'subcategory': 'Laptops',
        'brand': 'Acer',
        'image_url': 'https://example.com/images/acer-aspire.jpg',
        'link_url': 'https://example.com/products/acer-aspire',
        'stock': 30,
        'featured': False,
        'target_age_min': 18,
        'target_age_max': 40,
        'target_locations': ['Colombo', 'Kandy', 'Galle', 'Negombo', 'Matara'],
        'target_jobs': ['student', 'teacher', 'engineer'],
        'target_categories': ['student', 'young_adult', 'tech_enthusiast'],
        'keywords': ['laptop', 'budget', 'affordable', 'student', 'acer', 'computer'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Microsoft Surface Laptop 5',
        'description': 'Microsoft Surface Laptop 5, Intel Core i7, 16GB RAM, 512GB SSD. 13.5" PixelSense touchscreen. Premium design.',
        'price': 425000,
        'category': 'Electronics',
        'subcategory': 'Laptops',
        'brand': 'Microsoft',
        'image_url': 'https://example.com/images/surface-laptop.jpg',
        'link_url': 'https://example.com/products/surface-laptop',
        'stock': 8,
        'featured': False,
        'target_age_min': 25,
        'target_age_max': 50,
        'target_locations': ['Colombo'],
        'target_jobs': ['software engineer', 'business owner', 'teacher'],
        'target_categories': ['tech_enthusiast', 'tech_professional', 'established_professional'],
        'keywords': ['laptop', 'microsoft', 'surface', 'touchscreen', 'premium', 'professional'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Desktop PC - Custom Build',
        'description': 'Custom gaming/workstation PC. Intel Core i7, 32GB RAM, RTX 3060 Ti, 1TB NVMe SSD. Built to order.',
        'price': 325000,
        'category': 'Electronics',
        'subcategory': 'Computers',
        'brand': 'Custom',
        'image_url': 'https://example.com/images/custom-pc.jpg',
        'link_url': 'https://example.com/products/custom-pc',
        'stock': 20,
        'featured': False,
        'target_age_min': 20,
        'target_age_max': 40,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['software engineer', 'student', 'designer'],
        'target_categories': ['tech_enthusiast', 'tech_professional', 'electronics_buyer'],
        'keywords': ['desktop', 'pc', 'computer', 'gaming', 'workstation', 'custom build'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'iMac 24" M3 - All-in-One',
        'description': 'Apple iMac 24" with M3 chip, 8GB RAM, 256GB SSD. 4.5K Retina display. Perfect for home and office.',
        'price': 475000,
        'category': 'Electronics',
        'subcategory': 'Computers',
        'brand': 'Apple',
        'image_url': 'https://example.com/images/imac-24.jpg',
        'link_url': 'https://example.com/products/imac-24',
        'stock': 5,
        'featured': False,
        'target_age_min': 25,
        'target_age_max': 55,
        'target_locations': ['Colombo'],
        'target_jobs': ['designer', 'business owner', 'teacher'],
        'target_categories': ['tech_enthusiast', 'electronics_buyer', 'established_professional'],
        'keywords': ['imac', 'apple', 'desktop', 'computer', 'all-in-one', 'mac'],
        'created_at': datetime.utcnow()
    },
    
    # ==========================================
    # COURSES & EDUCATION (15 items)
    # ==========================================
    {
        'title': 'Python Programming Bootcamp',
        'description': 'Complete Python programming course from beginner to advanced. 12 weeks, hands-on projects. Job placement assistance.',
        'price': 45000,
        'category': 'Education',
        'subcategory': 'Programming',
        'brand': 'TechAcademy',
        'image_url': 'https://example.com/images/python-course.jpg',
        'link_url': 'https://example.com/courses/python',
        'stock': 50,
        'featured': True,
        'target_age_min': 18,
        'target_age_max': 40,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['student', 'engineer', 'teacher'],
        'target_categories': ['tech_enthusiast', 'course_buyer', 'student', 'job_seeker'],
        'keywords': ['python', 'programming', 'coding', 'software', 'course', 'training', 'bootcamp'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Full Stack Web Development Course',
        'description': 'Learn HTML, CSS, JavaScript, React, Node.js, MongoDB. 6-month comprehensive program. Build real projects.',
        'price': 75000,
        'category': 'Education',
        'subcategory': 'Programming',
        'brand': 'CodeMasters',
        'image_url': 'https://example.com/images/fullstack-course.jpg',
        'link_url': 'https://example.com/courses/fullstack',
        'stock': 40,
        'featured': True,
        'target_age_min': 20,
        'target_age_max': 35,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['student', 'software engineer', 'engineer'],
        'target_categories': ['tech_enthusiast', 'course_buyer', 'job_seeker', 'early_career'],
        'keywords': ['web development', 'fullstack', 'javascript', 'react', 'nodejs', 'programming', 'course'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Data Science & Machine Learning',
        'description': 'Master data science, Python, SQL, machine learning, AI. 4-month intensive program. Career guaranteed.',
        'price': 95000,
        'category': 'Education',
        'subcategory': 'Data Science',
        'brand': 'DataMinds',
        'image_url': 'https://example.com/images/data-science.jpg',
        'link_url': 'https://example.com/courses/data-science',
        'stock': 30,
        'featured': True,
        'target_age_min': 22,
        'target_age_max': 40,
        'target_locations': ['Colombo'],
        'target_jobs': ['software engineer', 'engineer', 'student'],
        'target_categories': ['tech_enthusiast', 'tech_professional', 'course_buyer', 'job_seeker'],
        'keywords': ['data science', 'machine learning', 'ai', 'python', 'course', 'analytics', 'training'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Digital Marketing Masterclass',
        'description': 'Complete digital marketing course. SEO, SEM, Social Media, Content Marketing, Analytics. 3 months.',
        'price': 35000,
        'category': 'Education',
        'subcategory': 'Marketing',
        'brand': 'MarketPro',
        'image_url': 'https://example.com/images/digital-marketing.jpg',
        'link_url': 'https://example.com/courses/digital-marketing',
        'stock': 60,
        'featured': False,
        'target_age_min': 22,
        'target_age_max': 45,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['business owner', 'manager', 'student'],
        'target_categories': ['business_owner', 'course_buyer', 'entrepreneur'],
        'keywords': ['digital marketing', 'seo', 'social media', 'marketing', 'course', 'online marketing'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Graphic Design Pro Course',
        'description': 'Master Adobe Photoshop, Illustrator, InDesign. Logo design, branding, UI/UX basics. Portfolio projects.',
        'price': 42000,
        'category': 'Education',
        'subcategory': 'Design',
        'brand': 'DesignHub',
        'image_url': 'https://example.com/images/graphic-design.jpg',
        'link_url': 'https://example.com/courses/graphic-design',
        'stock': 35,
        'featured': False,
        'target_age_min': 18,
        'target_age_max': 35,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['student', 'designer', 'teacher'],
        'target_categories': ['course_buyer', 'student', 'young_adult'],
        'keywords': ['graphic design', 'photoshop', 'design', 'creative', 'course', 'adobe'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'English Speaking Course',
        'description': 'Improve English speaking confidence. IELTS/TOEFL preparation. Small batches. Native trainers.',
        'price': 18000,
        'category': 'Education',
        'subcategory': 'Language',
        'brand': 'SpeakWell',
        'image_url': 'https://example.com/images/english-course.jpg',
        'link_url': 'https://example.com/courses/english',
        'stock': 80,
        'featured': False,
        'target_age_min': 16,
        'target_age_max': 45,
        'target_locations': ['Colombo', 'Kandy', 'Galle', 'Negombo'],
        'target_jobs': ['student', 'teacher', 'engineer'],
        'target_categories': ['student', 'course_buyer', 'young_adult'],
        'keywords': ['english', 'language', 'speaking', 'ielts', 'course', 'communication'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Professional Photography Course',
        'description': 'Learn DSLR photography, editing, lighting, composition. Wedding & event photography. Practical training.',
        'price': 32000,
        'category': 'Education',
        'subcategory': 'Photography',
        'brand': 'PhotoPro',
        'image_url': 'https://example.com/images/photography.jpg',
        'link_url': 'https://example.com/courses/photography',
        'stock': 25,
        'featured': False,
        'target_age_min': 18,
        'target_age_max': 40,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['student', 'business owner', 'teacher'],
        'target_categories': ['course_buyer', 'young_adult', 'entrepreneur'],
        'keywords': ['photography', 'camera', 'dslr', 'course', 'photo editing', 'creative'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Accounting & Finance Course',
        'description': 'Learn accounting principles, financial management, Excel, QuickBooks. Perfect for small business owners.',
        'price': 28000,
        'category': 'Education',
        'subcategory': 'Business',
        'brand': 'FinanceAcademy',
        'image_url': 'https://example.com/images/accounting.jpg',
        'link_url': 'https://example.com/courses/accounting',
        'stock': 45,
        'featured': False,
        'target_age_min': 22,
        'target_age_max': 50,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['business owner', 'manager', 'student'],
        'target_categories': ['business_owner', 'course_buyer', 'management'],
        'keywords': ['accounting', 'finance', 'business', 'bookkeeping', 'course', 'management'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Cybersecurity Essentials',
        'description': 'Learn network security, ethical hacking, penetration testing. Industry-recognized certifications.',
        'price': 65000,
        'category': 'Education',
        'subcategory': 'IT Security',
        'brand': 'SecureLearn',
        'image_url': 'https://example.com/images/cybersecurity.jpg',
        'link_url': 'https://example.com/courses/cybersecurity',
        'stock': 20,
        'featured': True,
        'target_age_min': 22,
        'target_age_max': 40,
        'target_locations': ['Colombo'],
        'target_jobs': ['software engineer', 'engineer', 'it professional'],
        'target_categories': ['tech_enthusiast', 'tech_professional', 'course_buyer'],
        'keywords': ['cybersecurity', 'hacking', 'security', 'networking', 'course', 'it'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Mobile App Development - iOS & Android',
        'description': 'Build mobile apps with React Native. Create apps for iOS and Android. 10-week intensive program.',
        'price': 55000,
        'category': 'Education',
        'subcategory': 'Programming',
        'brand': 'AppDev Institute',
        'image_url': 'https://example.com/images/mobile-dev.jpg',
        'link_url': 'https://example.com/courses/mobile-dev',
        'stock': 30,
        'featured': False,
        'target_age_min': 20,
        'target_age_max': 35,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['software engineer', 'student', 'engineer'],
        'target_categories': ['tech_enthusiast', 'course_buyer', 'job_seeker'],
        'keywords': ['mobile app', 'react native', 'ios', 'android', 'programming', 'course', 'development'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Video Editing with Adobe Premiere',
        'description': 'Professional video editing, color grading, motion graphics. Create stunning videos for YouTube, TikTok.',
        'price': 38000,
        'category': 'Education',
        'subcategory': 'Video Production',
        'brand': 'MediaPro',
        'image_url': 'https://example.com/images/video-editing.jpg',
        'link_url': 'https://example.com/courses/video-editing',
        'stock': 35,
        'featured': False,
        'target_age_min': 18,
        'target_age_max': 35,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['student', 'designer', 'business owner'],
        'target_categories': ['course_buyer', 'young_adult', 'entrepreneur'],
        'keywords': ['video editing', 'premiere', 'adobe', 'youtube', 'content creation', 'course'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'UI/UX Design Bootcamp',
        'description': 'User interface and user experience design. Figma, Adobe XD. Create stunning app and web designs.',
        'price': 48000,
        'category': 'Education',
        'subcategory': 'Design',
        'brand': 'UX Academy',
        'image_url': 'https://example.com/images/uiux-course.jpg',
        'link_url': 'https://example.com/courses/uiux',
        'stock': 25,
        'featured': True,
        'target_age_min': 20,
        'target_age_max': 35,
        'target_locations': ['Colombo'],
        'target_jobs': ['designer', 'software engineer', 'student'],
        'target_categories': ['tech_enthusiast', 'course_buyer', 'job_seeker'],
        'keywords': ['ui ux', 'design', 'figma', 'user experience', 'app design', 'course'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Business English & Communication',
        'description': 'Master business communication, emails, presentations, meetings. Corporate English for professionals.',
        'price': 22000,
        'category': 'Education',
        'subcategory': 'Language',
        'brand': 'BizSpeak',
        'image_url': 'https://example.com/images/business-english.jpg',
        'link_url': 'https://example.com/courses/business-english',
        'stock': 50,
        'featured': False,
        'target_age_min': 22,
        'target_age_max': 50,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['manager', 'business owner', 'engineer'],
        'target_categories': ['management', 'course_buyer', 'established_professional'],
        'keywords': ['business english', 'communication', 'professional', 'corporate', 'course'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Excel & Power BI for Data Analysis',
        'description': 'Advanced Excel, Power BI, data visualization, business intelligence. Transform data into insights.',
        'price': 30000,
        'category': 'Education',
        'subcategory': 'Business',
        'brand': 'DataSkills',
        'image_url': 'https://example.com/images/excel-powerbi.jpg',
        'link_url': 'https://example.com/courses/excel-powerbi',
        'stock': 40,
        'featured': False,
        'target_age_min': 22,
        'target_age_max': 50,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['manager', 'business owner', 'engineer'],
        'target_categories': ['management', 'course_buyer', 'business_owner'],
        'keywords': ['excel', 'power bi', 'data analysis', 'business intelligence', 'course'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Entrepreneurship & Startup Course',
        'description': 'Start your own business. Business planning, funding, marketing, scaling. Mentorship included.',
        'price': 40000,
        'category': 'Education',
        'subcategory': 'Business',
        'brand': 'StartupLK',
        'image_url': 'https://example.com/images/entrepreneurship.jpg',
        'link_url': 'https://example.com/courses/entrepreneurship',
        'stock': 30,
        'featured': False,
        'target_age_min': 22,
        'target_age_max': 45,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['business owner', 'manager', 'student'],
        'target_categories': ['entrepreneur', 'business_owner', 'course_buyer'],
        'keywords': ['entrepreneurship', 'startup', 'business', 'entrepreneur', 'course', 'business plan'],
        'created_at': datetime.utcnow()
    },
    
    # ==========================================
    # SMARTPHONES & TABLETS (8 items)
    # ==========================================
    {
        'title': 'iPhone 15 Pro Max',
        'description': 'Apple iPhone 15 Pro Max 256GB. A17 Pro chip, titanium design, 48MP camera. Premium smartphone.',
        'price': 485000,
        'category': 'Electronics',
        'subcategory': 'Smartphones',
        'brand': 'Apple',
        'image_url': 'https://example.com/images/iphone-15-pro.jpg',
        'link_url': 'https://example.com/products/iphone-15-pro',
        'stock': 15,
        'featured': True,
        'target_age_min': 25,
        'target_age_max': 50,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['software engineer', 'doctor', 'business owner'],
        'target_categories': ['tech_enthusiast', 'electronics_buyer', 'established_professional'],
        'keywords': ['iphone', 'apple', 'smartphone', 'mobile', 'phone', 'premium'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Samsung Galaxy S24 Ultra',
        'description': 'Samsung Galaxy S24 Ultra 512GB. Snapdragon 8 Gen 3, 200MP camera, S Pen. Flagship Android phone.',
        'price': 425000,
        'category': 'Electronics',
        'subcategory': 'Smartphones',
        'brand': 'Samsung',
        'image_url': 'https://example.com/images/galaxy-s24.jpg',
        'link_url': 'https://example.com/products/galaxy-s24',
        'stock': 20,
        'featured': True,
        'target_age_min': 22,
        'target_age_max': 50,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['software engineer', 'business owner', 'doctor'],
        'target_categories': ['tech_enthusiast', 'electronics_buyer', 'mid_career_family'],
        'keywords': ['samsung', 'galaxy', 'android', 'smartphone', 'mobile', 'phone'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Google Pixel 8 Pro',
        'description': 'Google Pixel 8 Pro 256GB. Google Tensor G3, best camera, pure Android. AI features.',
        'price': 365000,
        'category': 'Electronics',
        'subcategory': 'Smartphones',
        'brand': 'Google',
        'image_url': 'https://example.com/images/pixel-8-pro.jpg',
        'link_url': 'https://example.com/products/pixel-8-pro',
        'stock': 12,
        'featured': False,
        'target_age_min': 25,
        'target_age_max': 45,
        'target_locations': ['Colombo'],
        'target_jobs': ['software engineer', 'engineer', 'business owner'],
        'target_categories': ['tech_enthusiast', 'electronics_buyer', 'tech_professional'],
        'keywords': ['pixel', 'google', 'android', 'smartphone', 'mobile', 'camera'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Xiaomi 13T Pro',
        'description': 'Xiaomi 13T Pro 512GB. Dimensity 9200+, 144Hz AMOLED, 120W charging. Value flagship.',
        'price': 195000,
        'category': 'Electronics',
        'subcategory': 'Smartphones',
        'brand': 'Xiaomi',
        'image_url': 'https://example.com/images/xiaomi-13t.jpg',
        'link_url': 'https://example.com/products/xiaomi-13t',
        'stock': 30,
        'featured': False,
        'target_age_min': 20,
        'target_age_max': 40,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['student', 'engineer', 'teacher'],
        'target_categories': ['tech_enthusiast', 'electronics_buyer', 'young_adult'],
        'keywords': ['xiaomi', 'android', 'smartphone', 'mobile', 'budget', 'phone'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'OnePlus 12',
        'description': 'OnePlus 12 256GB. Snapdragon 8 Gen 3, Hasselblad camera, 100W charging. Flagship killer.',
        'price': 265000,
        'category': 'Electronics',
        'subcategory': 'Smartphones',
        'brand': 'OnePlus',
        'image_url': 'https://example.com/images/oneplus-12.jpg',
        'link_url': 'https://example.com/products/oneplus-12',
        'stock': 18,
        'featured': False,
        'target_age_min': 22,
        'target_age_max': 40,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['software engineer', 'engineer', 'student'],
        'target_categories': ['tech_enthusiast', 'electronics_buyer', 'early_career'],
        'keywords': ['oneplus', 'android', 'smartphone', 'mobile', 'phone', 'flagship'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'iPad Air M2',
        'description': 'Apple iPad Air with M2 chip. 11" Liquid Retina display. Perfect for work and creativity.',
        'price': 245000,
        'category': 'Electronics',
        'subcategory': 'Tablets',
        'brand': 'Apple',
        'image_url': 'https://example.com/images/ipad-air.jpg',
        'link_url': 'https://example.com/products/ipad-air',
        'stock': 12,
        'featured': False,
        'target_age_min': 20,
        'target_age_max': 50,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['student', 'designer', 'business owner', 'teacher'],
        'target_categories': ['tech_enthusiast', 'electronics_buyer', 'student'],
        'keywords': ['ipad', 'tablet', 'apple', 'device', 'portable', 'work'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Samsung Galaxy Tab S9',
        'description': 'Samsung Galaxy Tab S9 256GB. Dynamic AMOLED 2X, S Pen included. Premium Android tablet.',
        'price': 195000,
        'category': 'Electronics',
        'subcategory': 'Tablets',
        'brand': 'Samsung',
        'image_url': 'https://example.com/images/galaxy-tab-s9.jpg',
        'link_url': 'https://example.com/products/galaxy-tab-s9',
        'stock': 15,
        'featured': False,
        'target_age_min': 18,
        'target_age_max': 50,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['student', 'teacher', 'business owner'],
        'target_categories': ['tech_enthusiast', 'electronics_buyer', 'student'],
        'keywords': ['samsung', 'tablet', 'android', 'galaxy tab', 'device'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Budget Smartphone Bundle',
        'description': 'Affordable smartphone with case and screen protector. Perfect for first-time users.',
        'price': 45000,
        'category': 'Electronics',
        'subcategory': 'Smartphones',
        'brand': 'Various',
        'image_url': 'https://example.com/images/budget-phone.jpg',
        'link_url': 'https://example.com/products/budget-phone',
        'stock': 50,
        'featured': False,
        'target_age_min': 16,
        'target_age_max': 35,
        'target_locations': ['Colombo', 'Kandy', 'Galle', 'Negombo', 'Matara'],
        'target_jobs': ['student', 'teacher'],
        'target_categories': ['student', 'young_adult'],
        'keywords': ['smartphone', 'budget', 'affordable', 'cheap', 'mobile', 'phone'],
        'created_at': datetime.utcnow()
    },
    
    # ==========================================
    # VEHICLES (5 items)
    # ==========================================
    {
        'title': 'Toyota Aqua 2020 - Hybrid',
        'description': 'Toyota Aqua 2020, hybrid, excellent fuel economy. Well maintained, single owner. Perfect city car.',
        'price': 5200000,
        'category': 'Vehicles',
        'subcategory': 'Cars',
        'brand': 'Toyota',
        'image_url': 'https://example.com/images/aqua-2020.jpg',
        'link_url': 'https://example.com/vehicles/aqua-2020',
        'stock': 3,
        'featured': True,
        'target_age_min': 25,
        'target_age_max': 55,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['engineer', 'doctor', 'business owner', 'manager'],
        'target_categories': ['vehicle_buyer', 'mid_career_family', 'established_professional'],
        'keywords': ['car', 'vehicle', 'toyota', 'aqua', 'hybrid', 'auto'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Honda Fit 2018 - GP5',
        'description': 'Honda Fit GP5 2018. Excellent condition, low mileage. Ideal for families.',
        'price': 4500000,
        'category': 'Vehicles',
        'subcategory': 'Cars',
        'brand': 'Honda',
        'image_url': 'https://example.com/images/fit-2018.jpg',
        'link_url': 'https://example.com/vehicles/fit-2018',
        'stock': 2,
        'featured': False,
        'target_age_min': 28,
        'target_age_max': 50,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['engineer', 'teacher', 'manager'],
        'target_categories': ['vehicle_buyer', 'mid_career_family'],
        'keywords': ['car', 'vehicle', 'honda', 'fit', 'family car', 'auto'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Suzuki Alto 2021',
        'description': 'Suzuki Alto 2021, brand new condition. Low fuel consumption. Perfect for beginners.',
        'price': 2800000,
        'category': 'Vehicles',
        'subcategory': 'Cars',
        'brand': 'Suzuki',
        'image_url': 'https://example.com/images/alto-2021.jpg',
        'link_url': 'https://example.com/vehicles/alto-2021',
        'stock': 5,
        'featured': False,
        'target_age_min': 22,
        'target_age_max': 40,
        'target_locations': ['Colombo', 'Kandy', 'Galle', 'Negombo'],
        'target_jobs': ['teacher', 'engineer', 'student'],
        'target_categories': ['vehicle_buyer', 'early_career', 'young_adult'],
        'keywords': ['car', 'vehicle', 'suzuki', 'alto', 'budget', 'auto', 'small car'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Yamaha FZ-S 2022 - Bike',
        'description': 'Yamaha FZ-S 150cc, 2022 model. Low mileage, excellent condition. Stylish commuter bike.',
        'price': 485000,
        'category': 'Vehicles',
        'subcategory': 'Motorcycles',
        'brand': 'Yamaha',
        'image_url': 'https://example.com/images/fz-s.jpg',
        'link_url': 'https://example.com/vehicles/fz-s',
        'stock': 8,
        'featured': False,
        'target_age_min': 18,
        'target_age_max': 35,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['student', 'engineer', 'teacher'],
        'target_categories': ['vehicle_buyer', 'young_adult', 'early_career'],
        'keywords': ['bike', 'motorcycle', 'yamaha', 'vehicle', 'two wheeler'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Honda PCX 160 - Scooter',
        'description': 'Honda PCX 160 automatic scooter. Comfortable, fuel efficient. Perfect for city rides.',
        'price': 675000,
        'category': 'Vehicles',
        'subcategory': 'Motorcycles',
        'brand': 'Honda',
        'image_url': 'https://example.com/images/pcx-160.jpg',
        'link_url': 'https://example.com/vehicles/pcx-160',
        'stock': 6,
        'featured': False,
        'target_age_min': 20,
        'target_age_max': 45,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['engineer', 'teacher', 'student'],
        'target_categories': ['vehicle_buyer', 'young_adult', 'early_career'],
        'keywords': ['scooter', 'bike', 'honda', 'vehicle', 'automatic', 'two wheeler'],
        'created_at': datetime.utcnow()
    },
    
    # ==========================================
    # PROPERTY & HOUSING (5 items)
    # ==========================================
    {
        'title': 'Apartment in Colombo 7 - 3BR',
        'description': 'Luxury 3-bedroom apartment in Colombo 7. Sea view, modern amenities, parking. Prime location.',
        'price': 45000000,
        'category': 'Property',
        'subcategory': 'Apartments',
        'brand': None,
        'image_url': 'https://example.com/images/apt-colombo7.jpg',
        'link_url': 'https://example.com/property/apt-colombo7',
        'stock': 1,
        'featured': True,
        'target_age_min': 30,
        'target_age_max': 60,
        'target_locations': ['Colombo'],
        'target_jobs': ['doctor', 'business owner', 'engineer'],
        'target_categories': ['property_seeker', 'established_professional', 'mid_career_family'],
        'keywords': ['apartment', 'property', 'house', 'home', 'real estate', 'colombo'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Land for Sale - Kandy',
        'description': '20 perches land in Kandy. Clear title, near main road. Perfect for building house.',
        'price': 8500000,
        'category': 'Property',
        'subcategory': 'Land',
        'brand': None,
        'image_url': 'https://example.com/images/land-kandy.jpg',
        'link_url': 'https://example.com/property/land-kandy',
        'stock': 1,
        'featured': True,
        'target_age_min': 30,
        'target_age_max': 65,
        'target_locations': ['Kandy', 'Colombo'],
        'target_jobs': ['business owner', 'doctor', 'engineer'],
        'target_categories': ['property_seeker', 'established_professional', 'business_owner'],
        'keywords': ['land', 'property', 'real estate', 'plot', 'kandy', 'investment'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'House for Rent - Negombo',
        'description': '2-storey house for rent in Negombo. 3 bedrooms, 2 bathrooms. Near beach. Rs. 85,000/month.',
        'price': 85000,
        'category': 'Property',
        'subcategory': 'Rentals',
        'brand': None,
        'image_url': 'https://example.com/images/house-negombo.jpg',
        'link_url': 'https://example.com/property/house-negombo',
        'stock': 1,
        'featured': False,
        'target_age_min': 25,
        'target_age_max': 50,
        'target_locations': ['Negombo', 'Colombo'],
        'target_jobs': ['engineer', 'teacher', 'manager'],
        'target_categories': ['property_seeker', 'mid_career_family', 'early_career'],
        'keywords': ['house', 'rent', 'rental', 'property', 'home', 'negombo'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Commercial Property - Galle',
        'description': 'Commercial building in Galle city. Ground + 2 floors. Ideal for showroom or office.',
        'price': 28000000,
        'category': 'Property',
        'subcategory': 'Commercial',
        'brand': None,
        'image_url': 'https://example.com/images/commercial-galle.jpg',
        'link_url': 'https://example.com/property/commercial-galle',
        'stock': 1,
        'featured': False,
        'target_age_min': 35,
        'target_age_max': 65,
        'target_locations': ['Galle', 'Colombo', 'Matara'],
        'target_jobs': ['business owner'],
        'target_categories': ['business_owner', 'property_seeker', 'entrepreneur'],
        'keywords': ['commercial', 'property', 'business', 'office', 'showroom', 'galle'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Apartment Sharing - Colombo',
        'description': 'Room available in shared apartment. Fully furnished, WiFi, utilities included. Rs. 25,000/month.',
        'price': 25000,
        'category': 'Property',
        'subcategory': 'Rentals',
        'brand': None,
        'image_url': 'https://example.com/images/room-sharing.jpg',
        'link_url': 'https://example.com/property/room-sharing',
        'stock': 2,
        'featured': False,
        'target_age_min': 20,
        'target_age_max': 35,
        'target_locations': ['Colombo'],
        'target_jobs': ['student', 'engineer', 'teacher'],
        'target_categories': ['student', 'young_adult', 'early_career'],
        'keywords': ['room', 'sharing', 'rent', 'apartment', 'accommodation', 'colombo'],
        'created_at': datetime.utcnow()
    },
    
    # ==========================================
    # MISCELLANEOUS (7 items)
    # ==========================================
    {
        'title': 'Home Fitness Equipment Bundle',
        'description': 'Complete home gym set. Dumbbells, resistance bands, yoga mat, exercise ball. Get fit at home.',
        'price': 35000,
        'category': 'Health & Fitness',
        'subcategory': 'Equipment',
        'brand': 'FitPro',
        'image_url': 'https://example.com/images/fitness-bundle.jpg',
        'link_url': 'https://example.com/products/fitness-bundle',
        'stock': 20,
        'featured': False,
        'target_age_min': 20,
        'target_age_max': 50,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['engineer', 'doctor', 'teacher', 'business owner'],
        'target_categories': ['health_focused', 'young_adult', 'mid_career_family'],
        'keywords': ['fitness', 'gym', 'exercise', 'health', 'workout', 'equipment'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Professional Camera - Canon EOS R6',
        'description': 'Canon EOS R6 mirrorless camera with 24-105mm lens. 20MP, 4K video. Professional photography.',
        'price': 685000,
        'category': 'Electronics',
        'subcategory': 'Cameras',
        'brand': 'Canon',
        'image_url': 'https://example.com/images/canon-r6.jpg',
        'link_url': 'https://example.com/products/canon-r6',
        'stock': 5,
        'featured': False,
        'target_age_min': 22,
        'target_age_max': 45,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['designer', 'business owner', 'teacher'],
        'target_categories': ['electronics_buyer', 'established_professional'],
        'keywords': ['camera', 'photography', 'canon', 'dslr', 'professional', 'video'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Smart Watch - Apple Watch Series 9',
        'description': 'Apple Watch Series 9. Fitness tracking, health monitoring, always-on display. Stay connected.',
        'price': 145000,
        'category': 'Electronics',
        'subcategory': 'Wearables',
        'brand': 'Apple',
        'image_url': 'https://example.com/images/apple-watch-9.jpg',
        'link_url': 'https://example.com/products/apple-watch-9',
        'stock': 12,
        'featured': False,
        'target_age_min': 20,
        'target_age_max': 50,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['software engineer', 'doctor', 'business owner'],
        'target_categories': ['tech_enthusiast', 'health_focused', 'electronics_buyer'],
        'keywords': ['smartwatch', 'watch', 'apple watch', 'fitness', 'wearable', 'health'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Gaming Console - PlayStation 5',
        'description': 'Sony PlayStation 5 with controller. Latest games, 4K gaming. In stock now.',
        'price': 225000,
        'category': 'Electronics',
        'subcategory': 'Gaming',
        'brand': 'Sony',
        'image_url': 'https://example.com/images/ps5.jpg',
        'link_url': 'https://example.com/products/ps5',
        'stock': 8,
        'featured': True,
        'target_age_min': 18,
        'target_age_max': 35,
        'target_locations': ['Colombo', 'Kandy'],
        'target_jobs': ['student', 'software engineer', 'engineer'],
        'target_categories': ['tech_enthusiast', 'young_adult', 'electronics_buyer'],
        'keywords': ['gaming', 'playstation', 'ps5', 'console', 'games', 'entertainment'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Wireless Headphones - Sony WH-1000XM5',
        'description': 'Sony WH-1000XM5 noise cancelling headphones. Best-in-class sound, 30-hour battery.',
        'price': 95000,
        'category': 'Electronics',
        'subcategory': 'Audio',
        'brand': 'Sony',
        'image_url': 'https://example.com/images/sony-headphones.jpg',
        'link_url': 'https://example.com/products/sony-headphones',
        'stock': 18,
        'featured': False,
        'target_age_min': 18,
        'target_age_max': 45,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['student', 'software engineer', 'teacher'],
        'target_categories': ['tech_enthusiast', 'electronics_buyer', 'young_adult'],
        'keywords': ['headphones', 'wireless', 'sony', 'audio', 'music', 'noise cancelling'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Office Furniture Bundle',
        'description': 'Complete office setup. Desk, ergonomic chair, filing cabinet. Work from home comfortably.',
        'price': 125000,
        'category': 'Furniture',
        'subcategory': 'Office',
        'brand': 'OfficeMax',
        'image_url': 'https://example.com/images/office-furniture.jpg',
        'link_url': 'https://example.com/products/office-furniture',
        'stock': 10,
        'featured': False,
        'target_age_min': 25,
        'target_age_max': 55,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['software engineer', 'business owner', 'teacher'],
        'target_categories': ['property_seeker', 'mid_career_family', 'established_professional'],
        'keywords': ['furniture', 'office', 'desk', 'chair', 'work from home', 'ergonomic'],
        'created_at': datetime.utcnow()
    },
    {
        'title': 'Solar Panel System - 5kW',
        'description': '5kW solar panel system with inverter. Reduce electricity bills. Complete installation included.',
        'price': 850000,
        'category': 'Home Improvement',
        'subcategory': 'Solar Energy',
        'brand': 'SolarLK',
        'image_url': 'https://example.com/images/solar-panel.jpg',
        'link_url': 'https://example.com/products/solar-panel',
        'stock': 15,
        'featured': False,
        'target_age_min': 30,
        'target_age_max': 65,
        'target_locations': ['Colombo', 'Kandy', 'Galle'],
        'target_jobs': ['business owner', 'doctor', 'engineer'],
        'target_categories': ['property_seeker', 'established_professional', 'business_owner'],
        'keywords': ['solar', 'panel', 'energy', 'electricity', 'home improvement', 'renewable'],
        'created_at': datetime.utcnow()
    }
]

print(f"\n📝 Creating {len(products)} products...")
print("-" * 60)

# Insert products
inserted_count = 0
for product in products:
    try:
        result = products_collection.insert_one(product)
        inserted_count += 1
        print(f"✅ Created: {product['title']} (Rs. {product['price']:,})")
    except Exception as e:
        print(f"❌ Error creating {product['title']}: {e}")

print("\n" + "=" * 60)
print(f"✨ Total products created: {inserted_count}")
print(f"📊 Categories:")
categories = {}
for p in products:
    cat = p['category']
    categories[cat] = categories.get(cat, 0) + 1

for cat, count in sorted(categories.items()):
    print(f"   - {cat}: {count} products")

print("\n🎉 Enhanced product seeding completed successfully!")
print("=" * 60)